name: Laravel

on:
  push:
    branches: [ "master", "develop", "production" ]
  pull_request:
    branches: [ "master", "develop", "production" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0 # Use an official MySQL Docker image
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: testrootpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v4
    - run: mysql -h 127.0.0.1 --port 3306 -u root -password -e 'CREATE DATABASE IF NOT EXISTS testdb;'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update Dependencies
      run: composer update
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install Doctrine
      run: composer require doctrine/dbal
    - name: Generate key
      run: php artisan key:generate
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DATABASE_NAME: testdb
        DATABASE_USERNAME: root
        DATABASE_ENDPOINT: 127.0.0.1
        DATABASE_PASSWORD: testrootpass
      run: php artisan test
